version: '3.8'

services:
  # PostgreSQL for Rails services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: secret_santa_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for Sidekiq (if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
