version: '3.8'

services:
  # PostgreSQL for Rails services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: secret_santa_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for Sidekiq (if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # UI Service for local development
  ui-service:
    build: ./ui-service
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
